### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by brice-morin** [steelbreeze/state.js#11]
According to RELEASE.MD, it seems latest version is 5.3.1.

According to NPM, it seems latest version is 3.5.3.

I was so far using version 4.1.5 and was thinking about migrating to the latest version, which I guess should be in the 5.x.y

Can you tell me what version to use and why versions seems to have been decremented at some point... or is that just a typo in package.json, where 3.5.3 should be 5.3.3?

**Comment by mesmo** [comment]
Good morning Brice,

My most sincere apologies; I had a dyslexic moment when performing some releases over the weekend.

Should be all consistent at v5.3.4 now.


Again, sorry; but good to hear from you :-)

Kind regards,
David.

**Comment by brice-morin** [comment]
No problem, every one can make mistakes ;-) Good to see you always fix my issues quickly :-)

**Comment by brice-morin** [comment]
5.3.x works perfectly, our [ThingML](http://thingml.org) compiler is now migrated to that version and all our tests passes. Keep up the good work!

**Comment by mesmo** [comment]
That's great to hear - thanks for the update.
