### ISSUE TITLE
state.js errors in ie8

### ISSUE THREAD

**Issue by cormac** [steelbreeze/state.js#16]
Trying `state.js` out on a project that (urrgh) supports ie8. looks like it's the `console.error` statements causing the issue. Will post more info when I have it.

**Comment by cormac** [comment]
opening the [example page](https://cdn.rawgit.com/steelbreeze/state.js/master/examples/browser/test.html) gives us some more useful errors.
The transpiled version of the else transition seems to be throwing the error
https://github.com/steelbreeze/state.js/blob/master/lib/state.js#L657

**Comment by cormac** [comment]
yes, so it's the use of the else keyword in the function prototype that does the damage :disappointed:

**Comment by mesmo** [comment]
Hi Coramc,
Thanks for the report... I think you've uncovered two issues here in IE8 (something that I must confess I've not tested).
Yes, the IE8 JS engine gets confused with ```else``` as a method, but there's also something a little bigger going on with the code that browserify emits that IE8 is not happy with.
I will take a look and see if there's a possible fix that's not too disruptive to others.

**Comment by mesmo** [comment]
Looking further into this there's a bunch of other issues beyond those mentioned above; e.g. there looks to be no implementation of ```Array.prototype.reduce``` available in IE8.

I've created an IE8 branch and will continue to investigate there.

**Comment by mesmo** [comment]
Hi Cormac,
I've added the required polyfills for the various ```Array``` methods I rely on that IE8 does not support. The example still does not work, but I think this is now more of an issue in the example code.

**Comment by mesmo** [comment]
This issue has now been fixed on the IE8 branch; the following changes are only applicable to this branch.
* The ```Transition.else``` method is renamed to ```Transition.Else```.
* The target attribute in the HTML script element when pulling state.js into your page is not supported; instead, the API is always bound to the global variable fsm.
* Polyfills have been added to cater for the lesser implementation of ```Array````.

**Comment by cormac** [comment]
Hey David, thanks for addressing this so quickly
