### ISSUE TITLE
if i want use the origin object in effect,entry and exit,how should i do?

### ISSUE THREAD

**Issue by dorado-lmz** [steelbreeze/state.js#17]
* i see the test file in that Transition.effect,State.entry and State.exit just can modify global variable,but i think we want to modify the Transiton Object or State Object in most cast. Is there some solution?

**Comment by mesmo** [comment]
I'm sorry but I do not understand your question/issue - could you explain further.

**Comment by dorado-lmz** [comment]
```javascript
target.to(target).when(function (message) { return message === "external"; }).effect(function (message, instance) { instance.transitionCount++; });
```
*this is a chian style usecase. i want to use **this** in function called effect. I wish The **this** refer to Transition.
> for example Jquery , `$("#btn_id").click(function(){$(this)})`,in the code,this refer to $("#btn_id").i mean Transition.effect should be like jquery

**Comment by mesmo** [comment]
Take a look at the source code for the example at https://state.software - this shows state.js being used with jquery.
