### ISSUE TITLE
Dynamic addition/removal of regions, states, etc

### ISSUE THREAD

**Issue by brice-morin** [steelbreeze/state.js#20]
Hi,

Is it possible to dynamically update the state machine, after it has been initialized and while it is running? Actually, I do not need full flexibility, but basically the ability to dynamically instantiate regions. This way I could handle sessions e.g. when a client connects. Since I cannot tell how many clients will connect in advance, static regions is not suitable.

Is it possible now?

If not, do you think it would be feasible to implement those dynamic regions/sessions? 

Thanks!

Brice.

**Comment by mesmo** [comment]
Hi Brice,

It is possible to make additive changes to the machine: just add new Regions, Vertices and Transitions as required, then the next time you evaluate a message, the machine will detect the updated model automatically reinitialise itself. 

How’s ThingML going -  getting good take-up?

Cheers, David.

**Comment by brice-morin** [comment]
Hi,

Great, I will try that next week. Also, are the changes additive only? Or is it possible to also remove regions, etc. As I mentioned, the idea would be to support some sort of sessions. When a session is over, it is over. Maybe a similar session while re-happen in the future (in this case we could reuse the region) but maybe not (in this case it would just be memory overhead and we risk saturating memory after a while).

As for ThingML, we start to get some users, in particular using our JS compiler targeting state.js ;-) But I would not really call it a take-up, yet. 

Cheers,

Brice.

**Comment by mesmo** [comment]
Hi Brice,
Dynamic removal of vertices and regions is not currently supported as the state machine model does not have any awareness of the active state configuration of the state machines instances, and therefore cannot warn if the state or region being deleted is active in an instance.

I can add this feature with warnings and caveats...

But, I'd recommend avoiding this if you can. If you have a server and client sessions, I'd suggest two separate state machine models, one for the server and one for the sessions (having a state machine instance for each session); they can communicate be sending each other messages.

Cheers, David

**Comment by brice-morin** [comment]
Well, my intention was not to remove anything "brutally", but make sure that a region that has reached a final state can actually be garbage collected (*i.e.* not contained anymore in any arrays, etc). I guess it should then be possible to safely remove an element that [`isComplete`](https://github.com/steelbreeze/state.js/blob/master/src/runtime/isComplete.ts). It it is not complete, it seems fair enough not to allow the removal of this element. It is up to the designer of the state machine to send the proper messages so that a "session" will actually reach the final state.

What do you think?

**Comment by brice-morin** [comment]
OK, I think I will go with dynamic instantiation and remove of components, each containing it own state machine.

**Comment by mesmo** [comment]
Hi Brice,

I am working on removal of elements; as usual, its a little more complicated than initially predicted as I need to ensure I also delete any transitions associated with the removed vertices.

Cheers, David.
