### ISSUE TITLE
Chained triggers not supported

### ISSUE THREAD

**Issue by brice-morin** [steelbreeze/state.js#22]
Hi,

It seems it is a bug in state.js (or I would call it a limitation as it apply to a pretty seldom situation). Let's say I have a state S1 with one internal transition IT and on transition (to state S2) T.

Let's say that IT and T both define a guard on a variable i. If `i == 0`, IT can be triggered. if `i > 0` T can be triggered. Let's say that IT is triggered, and in the action of IT we increment i, i will then be equal to 1, which IMHO, should trigger T right away (if there is no other condition than i > 0 in its guard). 

It seems that this is not the case now in state.js. Basically, when a transition is triggered, we should check if a transition can be triggered, without waiting for the reception of an event.

What do you think?

**Comment by mesmo** [comment]
Hi Brice,

I understand the issue and how I can fix it (add the logic to raise a _completion event_ after the internal transition action has executed), but I'm wondering if this is the correct thing to do?

Looking at the [UML Superstructure Specification](http://www.omg.org/spec/UML/2.4.1/Superstructure/PDF/), it states the following regarding internal transitions:

> An internal transition executes without exiting or re-entering the state in which it is defined. This is true even if the state machine is in a nested state within this state.

And then regarding completion transitions and completion events:

> A completion transition is a transition originating from a state or an exit point but which does not have an explicit trigger, although it may have a guard defined. A completion transition is implicitly triggered by a completion event. In case of a leaf state, a completion event is generated once the entry actions and the internal activities (“do” activities) have been completed.

So, as an internal transition executes without exiting or re-entering the state I feel it should not raise the completion event and therefore will not test for completion transitions.

I think a simple work around would be to change your internal transition to a self transition (specifying S1 as both the source and target of TI) - I'd imagine this should have the desired effect.

Happy do discuss more...

Kind regards,
David

**Comment by brice-morin** [comment]
Ok. Let me think about it and discuss it with some colleagues tomorrow. I think it is good to stick to the UML semantics, so we might revise our semantics. I'll come back to you tomorrow.

**Comment by mesmo** [comment]
Another question - are you expecting IT to be evaluated after successful entry to S1?

**Comment by brice-morin** [comment]
Yes, that is what I expect.

**Comment by mesmo** [comment]
Right now, the library doesn't; I'm trying to research what the UML intent is in this case...

**Comment by mesmo** [comment]
Morning Brice,

I've taken a look at the latter issue and see no reason why an internal transition should not be triggered by a completion event so I'll look to create a fix for this as soon as possible.

**Comment by brice-morin** [comment]
Sounds great! As usual, thank you for the rapid handling of issues :-)

**Comment by mesmo** [comment]
Correction: I've just mocked up your scenarios and can confirm that the internal transition evaluated and its behaviour is executed as you'd expect.

**Comment by brice-morin** [comment]
You mean in the current version? Is it triggering IT and then T right away?

**Comment by mesmo** [comment]
The current version will evaluate and invoke IT on entry to S1, but will not go on to evaluate T as per my initial post - [here](https://github.com/steelbreeze/state.js/blob/master/test/brice2.js) is the mock up.

**Comment by mesmo** [comment]
Morning Brice,
I've added a switch ```internalTransitionsTriggerCompletion``` to enable the desired behaviour. By default it is turned off but can easily be turned on. 

Take a look at the [new test](https://github.com/steelbreeze/state.js/blob/master/test/brice2.js) for details.

**Comment by mesmo** [comment]
Released v5.6.7 with the switch above.

**Comment by brice-morin** [comment]
Great, then I will try tomorrow :-)

2016-05-03 21:22 GMT+02:00 David Mesquita-Morris <notifications@github.com>:
