### ISSUE TITLE
Serialization of Instances

### ISSUE THREAD

**Issue by Dessix** [steelbreeze/state.js#23]
The [StateMachineInstance documentation](https://state.software/docs/classes/statemachineinstance.html) mentions that an instance could be written which can serialize to JSON, but doesn't really give any details on how such an attempt would be performed. I need to store the current state of a machine across multiple servers that will instantiate it the model and load the instance, so serialization is quite important for my needs.

Could you provide some guidance on how this could be done without breaking assumptions of the architecture?

**Comment by mesmo** [comment]
[StateMachineInstance](http://state.software/docs/classes/statemachineinstance.html) is an implementation of the [IInstance](http://state.software/docs/interfaces/iinstance.html) interface which is used to manage the _active state configuration_ of a state machine instance; this interface is what the rest of the state machine engine works with. It relies on the two methods [getCurrent](http://state.software/docs/interfaces/iinstance.html#getcurrent), [setCurrent](http://state.software/docs/interfaces/iinstance.html#setcurrent) which just store and return the last known [State](http://state.software/docs/classes/state.html) for a given [Region](http://state.software/docs/classes/region.html) - it also requires the boolean property [isTerminated](http://state.software/docs/interfaces/iinstance.html#isterminated). If you create a class that implements this interface then instances of it can be passed into the [initialise](http://state.software/docs/index.html#initialise) and [evaluate](http://state.software/docs/index.html#evaluate) functions. 

The [StateMachineInstance](http://state.software/docs/classes/statemachineinstance.html) class was intended as a simple example to show how to manage the _active state configuration_ using a simple associative array.  If you copy the code and manage your JSON object in the  [getCurrent](http://state.software/docs/interfaces/iinstance.html#getcurrent), [setCurrent](http://state.software/docs/interfaces/iinstance.html#setcurrent) methods you should be fine.

**Comment by mesmo** [comment]
Take a look at [JSONInstance.ts](https://github.com/steelbreeze/state.js/blob/master/examples/node/JSONInstance.ts); this is an implementation as described above.

See it in use in [player.ts](https://github.com/steelbreeze/state.js/blob/master/examples/node/player.ts).
