### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by joeloyj** [steelbreeze/state.js#31]
https://state.software/docs/ gives 404

**Comment by mesmo** [comment]
Fixed.  As v6 is currently in development, there are now two sets of documentation https://state.software/docs/v5/ and https://state.software/docs/v6/ - I've added a redirect to default to v5.

**Comment by joeloyj** [comment]
both sites seem to be down at the moment.

**Comment by mesmo** [comment]
Hi, the doc's have moved domain to https://steelbreeze.net/state/docs/v5/ and https://steelbreeze.net/state/docs/v6/
