### ISSUE TITLE
Are you be interested in StateMachine Drawing?

### ISSUE THREAD

**Issue by zhangbowei** [steelbreeze/state.js#33]
I'm developping a Web application, which can draw StateMachine.
And it will be merged  with state.js in the follow-up work.

Do you have any suggestions?

[Demo Link](https://github.com/zhangbowei/StateChart)
![](https://ww3.sinaimg.cn/large/006tNbRwly1ffvkruy54hg30z50hj1fo.gif)

**Comment by mesmo** [comment]
Thanks for the interest in state.js. It is my intent to keep it small and focused on being an executable state machine engine so I will not be merging in any functionality such as this, however you are free to use state.js as you wish.
