### ISSUE TITLE
Suggestion: link to examples that work from Repo not just PNGs

### ISSUE THREAD

**Issue by pscott-au** [steelbreeze/state.js#36]
Browsed on in and fiddled about hoping to find a link to a working example but moved on. As you're using Github Pages it should be reasonably easy to include a link to a working example to allow browsers to evaluate suitability.

**Comment by mesmo** [comment]
Thanks for the feedback - you're right that the examples are woefully outdated... the state.js repo is now deprecated so please see the version [@steelbreeze/state](https://github.com/steelbreeze/state/). In that version I have now written a working example in Github Pages using an SVG representation of the same machine where the state entry/exit behaviour colours the SVG elements: https://steelbreeze.net/state/
