### ISSUE TITLE
Link in  README.md to Documentation is broken

### ISSUE THREAD

**Issue by WillCPP** [steelbreeze/state.js#37]
The link to the documentation is broken.

https://steelbreeze.net/state/docs/

Results in a 404

**Comment by mesmo** [comment]
Hi @WillCPP,

This version has been deprecated for quite some time and moved over to https://github.com/steelbreeze/state where there is good documentation.

I will however see what I can do about recreating documentation for this version...

**Comment by davidwcmorris** [comment]
Documentation recreated and can be found here: http://steelbreeze.net/state/api/v5/

Link in README updated.
